version: "3.8"
services:
  apiusersmongo:
    build: .
    container_name: "api-users-mongo"
    ports:
      - 8080:8080
    networks:
      - app_network
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017
    networks:
      - app_network

networks:
  app_network:
    driver: bridge